baseURL = "/"
languageCode = "en-us"
title = "Version Control for Researchers"
description = "Materials for R-RSE workshop on 'Version Control for Researchers'"
pygmentsUseClasses=true
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "index\\.html", '\.knit\.md$', '\.utf8\.md$']


[module]
  [[module.imports]]
    path = "github.com/matcornic/hugo-theme-learn"
  [[module.imports]]
    path = "github.com/dzello/reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Version Control for Researchers"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/r-rse/git-github-zero-to-hero"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Online Learning Platforms"
url = "/platforms"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='far fa-fw fa-copy'></i> Snippets"
url = "/snippets"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 40

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-certificate'></i> CC-BY Licence"
url = "https://creativecommons.org/licenses/by/4.0/"
weight = 50

[params]
  editURL = "https://github.com/r-rse/git-github-zero-to-hero/edit/master/content/"
  description = "Version Control for Researchers"
  author = "Anna Krystalli, R-RSE"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "rse-learn"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.reveal_hugo]
 theme = "white"
 load_default_plugins = false
 plugins = [
   "reveal-js/plugin/zoom-js/zoom.js",
   "reveal-js/plugin/notes/notes.js",
 ]
